package app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller //identify class as a controller
@RequestMapping(path="/demo") //url pattern to reach this is /demo
public class MainController {
    @Autowired //To get teh bean called userRepository, which is auto-generated by spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/add") //MAP only get requests
    public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
        //@Response body means the returned String is the response, not a view name
        //@Request Param means it is a parameter from a GET or POST request
        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        //This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
